package interfacesUI;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import metodos.Asignacion3;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author villa
 */
public class frmAsignacion3 extends javax.swing.JFrame {

    /**
     * Creates new form frmAsignacion3
     */
    
    Asignacion3 asig = new Asignacion3();
    DefaultTableModel model1,model2;
    
    public frmAsignacion3() {
        initComponents();
        this.setLocationRelativeTo(null);
        pnlTabla.show(false);
        btnMostrarModel1.setEnabled(false);
        btnMostrarModel2.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtValorVerdadero = new javax.swing.JTextField();
        txtValorMetodo1 = new javax.swing.JTextField();
        txtValorMetodo2 = new javax.swing.JTextField();
        txtError1 = new javax.swing.JTextField();
        txtConclusion = new javax.swing.JTextField();
        txtError2 = new javax.swing.JTextField();
        txtCifras = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        btnMostrarModel1 = new javax.swing.JButton();
        btnMostrarModel2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTabla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla1.setModel(new DefaultTableModel(new Object[]{"Iteracion", "Resultado", "Error Aproximado"}, 0));
        jScrollPane1.setViewportView(tabla1);

        pnlTabla.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 360, 430));

        jButton3.setText("X");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        pnlTabla.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, -1));

        getContentPane().add(pnlTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingrese la cifras significativas:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("valor verdadero");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Valor metodo 1");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Valor metodo 2");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Error 1");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Error 2");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Concusion");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, 20));

        txtValorVerdadero.setEditable(false);
        jPanel1.add(txtValorVerdadero, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 155, 20));

        txtValorMetodo1.setEditable(false);
        jPanel1.add(txtValorMetodo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 155, 20));

        txtValorMetodo2.setEditable(false);
        jPanel1.add(txtValorMetodo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 155, 20));

        txtError1.setEditable(false);
        jPanel1.add(txtError1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 155, 20));

        txtConclusion.setEditable(false);
        jPanel1.add(txtConclusion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 260, 20));

        txtError2.setEditable(false);
        jPanel1.add(txtError2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 155, 20));
        jPanel1.add(txtCifras, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 51, 20));

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, 20));

        btnMostrarModel1.setText(">");
        btnMostrarModel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarModel1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnMostrarModel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 40, 20));

        btnMostrarModel2.setText(">");
        btnMostrarModel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarModel2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnMostrarModel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 40, 20));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.jpg"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-170, -50, 510, 310));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
       if(txtCifras.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Ingrese la cantidad de cifras.");
       }else{
        btnMostrarModel1.setEnabled(true);
        btnMostrarModel2.setEnabled(true);
        txtValorVerdadero.setText(String.valueOf(asig.getVv()));
        model1 = asig.metodo1(Integer.parseInt(txtCifras.getText()),5);
        txtValorMetodo1.setText(String.valueOf(asig.getRes1()));
        txtError1.setText(String.valueOf(asig.getEr1()));
       }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnMostrarModel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarModel2ActionPerformed
        tabla1.setModel(model2);
        tabla1.sizeColumnsToFit(0);
        btnCalcular.show(false);
        btnMostrarModel1.show(false);
        btnMostrarModel2.show(false);
        txtCifras.show(false);
        pnlTabla.show(true);
    }//GEN-LAST:event_btnMostrarModel2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        pnlTabla.show(false);
        btnCalcular.show(true);
        btnMostrarModel1.show(true);
        btnMostrarModel2.show(true);
        txtCifras.show(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnMostrarModel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarModel1ActionPerformed
        tabla1.setModel(model1);
        tabla1.sizeColumnsToFit(0);
        btnCalcular.show(false);
        btnMostrarModel1.show(false);
        btnMostrarModel2.show(false);
        txtCifras.show(false);
        pnlTabla.show(true);
    }//GEN-LAST:event_btnMostrarModel1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAsignacion3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAsignacion3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAsignacion3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAsignacion3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAsignacion3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnMostrarModel1;
    private javax.swing.JButton btnMostrarModel2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlTabla;
    private javax.swing.JTable tabla1;
    private javax.swing.JTextField txtCifras;
    private javax.swing.JTextField txtConclusion;
    private javax.swing.JTextField txtError1;
    private javax.swing.JTextField txtError2;
    private javax.swing.JTextField txtValorMetodo1;
    private javax.swing.JTextField txtValorMetodo2;
    private javax.swing.JTextField txtValorVerdadero;
    // End of variables declaration//GEN-END:variables
}
